### ISSUE TITLE
Screencast configuring Glass in FC

### ISSUE THREAD

**Issue by luzpaz** [triplus/Glass#2]
This may be a nice to add to the README? 

[![OficineRobotica FreeCAD Customization Using Glass](http://img.youtube.com/vi/ny31diN1ZhM/0.jpg)](http://www.youtube.com/watch?v=ny31diN1ZhM)

**Comment by triplus** [comment]
Done.

https://forum.freecadweb.org/viewtopic.php?f=24&t=42453#p361157
